import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";

import { api } from "~/utils/api";

const CreatePostWizard = () => {

  const { user } = useUser();

  console.log(user);

  if (!user) return null;

  return <div className="flex gap-3 w-full">
    <img className="w-14 h-14 rounded-full" src={user.profileImageUrl} alt="Profile image" />
    <input placeholder="Tweet here!" className="bg-transparent grow outline-none" />
  </div>
}

const Home: NextPage = () => {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });

  const user = useUser();

  const { data, isLoading } = api.posts.getAll.useQuery();

  if (isLoading) return <div>Loading...</div>;

  if (!data) return <div>Something went wrong</div>;


  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
      <div className="h-full w-full border-x border-slate-400 md:max-w-2xl ">
        <div className="border-b border-slate-400 p-4">
            {!user.isSignedIn && <div className="flex justify-center"><SignInButton /></div>}
            {user.isSignedIn && <CreatePostWizard />}
        </div>
      </div>
      <div className="flex flex-col">
        {[...data]?.map((post) => (
         <div className="p-8 border-b border-slate-400" key={post.id}>{post.content}</div>
        ))}
      </div>
        <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" />
      </main>
    </>
  );
};

export default Home;
